POST http://localhost:3003/api/blogs  HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZWUzNDVmZTQyMDMyOTY2YzNhMTM1NiIsImlhdCI6MTcxMDE0Njk1M30.uoFUWOJ7pwhkq3-AdNR9mQBbASI6tQSAWO1lkt9jBE8
 
{
  "title": "Full Stack4",
  "author": "Ovini123456",
  "url": "http://test.com",
  "likes": "2"
}
###
POST http://localhost:3003/api/blogs  HTTP/1.1
content-type: application/json
 
{
  "title": "Full Stack4",
  "author": "Ovini123456",
  "url": "http://test.com",
  "likes": "2"
}